services:
  api:
    build: ./backend
    privileged: true
    devices:
      - "/dev/video2:/dev/video0"
      - "/dev/video0:/dev/video1"
      - "/dev/media0:/dev/media0"
      - "/dev/media1:/dev/media1"
      - "/dev/media2:/dev/media2"
      - "/dev/media5:/dev/media5"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - LIBCAMERA_LOG_LEVELS=*:3 # Optionnel : pour voir si libcamerify travaille
      - CONFIG_PATH=config/settings.json
      - DB_PATH=data/pi2p.db
    restart: always

  dashboard:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always
