services:
  api:
    build: ./backend
    privileged: true
    devices:
      - "/dev/video2:/dev/video98"  # Nappe -> /dev/video98
      - "/dev/video0:/dev/video99"  # USB -> /dev/video99
      - "/dev/media0:/dev/media98"
      - "/dev/media5:/dev/media99"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - CONFIG_PATH=config/settings.json
      - DB_PATH=data/pi2p.db
    restart: always

  dashboard:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always
