FROM python:3.11-slim

# Dépendances (libgl1 remplace l'ancienne libgl1-mesa-glx)
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Installation de opencv minimal
RUN pip install opencv-python-headless

COPY bridge_usb.py .

EXPOSE 8082

CMD ["python3", "-u", "bridge_usb.py"]
